
export const FETCH_PRODUCTS_REQUESTED = "FETCH_PRODUCTS_REQUESTED";
export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED";
export const PRODUCTS_CANOT_BE_FETCHED = "PRODUCTS_CANOT_BE_FETCHED";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QUANTITY = "ADJUST_QUANTITY";